### ISSUE TITLE
Error / exception failed to be wrapped

### ISSUE THREAD

**Issue by lifengmds** [acwazz/fastapi-responseschema#103] opened 2024-01-04 18:07 UTC
**Environment**
- `fastapi` version is: 0.104
- `fastapi-responseschema` version is: 2.1
- `python` version is: 3.9

**Describe the bug**
The lib failed to wrapper the validation error/exception from Pydantic 2.0, although I have specified error_response_schema.   http status: 400, 422, response: 
```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "username"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.5/v/missing"
        }
    ]
}
```

The wrap result from successful response is good.

```
class ResponseMetadata(BaseModel):
    error: bool = False
    message: Optional[str] = None
    pagination: Optional[PaginationMetadata] = None

T = TypeVar("T")

class ResponseSchema(AbstractResponseSchema[T], Generic[T]):
    data: T
    meta: ResponseMetadata

    @classmethod
    def from_exception(cls, reason, status_code, message: str = "Error", **others):
        return cls(
            data=reason,
            meta=ResponseMetadata(error=status_code >= 400, message=message)
        )

    @classmethod
    def from_api_route(
        cls, content: Any, status_code: int, description: Optional[str] = None, **others
    ):
        return cls(
            data=content,
            meta=ResponseMetadata(error=status_code >= 400, message=description)
        )

class PagedResponseSchema(AbstractPagedResponseSchema[T], Generic[T]):
    data: Union[Sequence[T], T]  
    meta: ResponseMetadata

    @classmethod
    def create(
            cls,
            items: Sequence[T],
            total: int,
            params: PaginationParams,
    ): 

        return cls(
            data=items,
            meta=ResponseMetadata(
                error=False,  
                pagination=PaginationMetadata.from_abstract_page_create(total=total, params=params)
            )
        )

    @classmethod
    def from_exception(cls, reason: T, status_code: int, message: str = "Error", **others):
        return cls(
            data=reason,
            meta=ResponseMetadata(error=status_code >= 400, message=message)
        )

    @classmethod
    def from_api_route(cls, content: Sequence[T], status_code: int, description: Optional[str] = None, **others): 
        return cls(error=status_code >= 400, data=content.data, meta=content.meta)
    

class StandardAPIRoute(SchemaAPIRoute):
    response_schema = ResponseSchema
    error_response_schema = ResponseSchema

class PagedRoute(PagedSchemaAPIRoute):
    response_schema = ResponseSchema
    paged_response_schema = PagedResponseSchema

app.router.route_class = StandardAPIRoute
```

**Comment by acwazz** [comment] 2024-01-19 07:33
Assuming the issue Is solved, I'm closing the ticket

**Closed** 2024-01-19 07:33 UTC
Labels: question

**Comment by lifengmds** [comment] 2024-02-08 14:32
I just noticed the reply, thank you very much, it solved my problem.
